apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: keycloakdb
    app.kubernetes.io/name: keycloak
  name: keycloak
  namespace: keycloakdb
spec:
  host: keycloak-keycloakdb.apps.tk2s6gya.eastus.aroapp.io
  port:
    targetPort: port-1
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: keycloak
    weight: 100
  wildcardPolicy: None
