apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: keycloakdb
    app.kubernetes.io/name: keycloak
  name: keycloak
  namespace: keycloakdb
spec:
  clusterIP: 172.30.212.33
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: keycloak
  sessionAffinity: None
  type: ClusterIP
